AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - spec/dummy/bin/**/*
    - spec/dummy/config/**/*
    - spec/dummy/db/**/*

Documentation:
  Exclude:
    - spec/**/*

StringLiterals:
  EnforcedStyle: double_quotes
