language: ruby
rvm:
  - 2.2.2
before_install:
  - gem update --system
  - gem update bundler
install: "bundle install"
script: RAILS_ENV=test bundle exec rake app:db:drop app:db:create app:db:migrate; bundle exec rake
